name: CI/CD Telegram Bot

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        VERSION="v1.0.0-$(git rev-parse --short HEAD)"
        IMAGE="ghcr.io/${{ github.repository_owner }}/telegram-bot:${VERSION}-linux-amd64"
        echo "Building image: $IMAGE"
        docker build --build-arg VERSION=$VERSION -t $IMAGE .
        docker push $IMAGE

    - name: Update Helm values.yaml
      run: |
        VERSION="v1.0.0-$(git rev-parse --short HEAD)"
        sed -i "s/tag: .*/tag: \"${VERSION}\"/" helm/telegram-bot/values.yaml
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git commit -am "ci: update Helm tag to ${VERSION}" || echo "No changes"
        git push || echo "Push failed"

    - name: Trigger ArgoCD sync (optional)
      if: ${{ secrets.ARGOCD_WEBHOOK_URL != '' }}
      run: |
        curl -X POST ${{ secrets.ARGOCD_WEBHOOK_URL }}

