name: CI/CD Telegram Bot

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: |
        VERSION="v1.0.0-$(git rev-parse --short HEAD)"
        IMAGE="ghcr.io/merida39/telegram-bot:${VERSION}-linux-amd64"
        docker build --build-arg VERSION=$VERSION -t $IMAGE .
        docker push $IMAGE

    - run: |
        VERSION="v1.0.0-$(git rev-parse --short HEAD)"
        sed -i "s/tag: .*/tag: \"${VERSION}\"/" helm/telegram-bot/values.yaml
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git commit -am "ci: update image tag to ${VERSION}" || echo "no changes"
        git push || echo "push failed"

    - run: |
        curl -X POST ${{ secrets.ARGOCD_WEBHOOK_URL }}
