name: CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          VERSION="v1.0.0-$(git rev-parse --short HEAD)"
          IMAGE="ghcr.io/merida39/telegram-bot:${VERSION}-linux-amd64"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Update Helm values.yaml
        run: |
          VERSION="v1.0.0-$(git rev-parse --short HEAD)-linux-amd64"
          sed -i "s|tag:.*|tag: \"${VERSION}\"|" helm/telegram-bot/values.yaml

      - name: Commit updated Helm values.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/telegram-bot/values.yaml
          git commit -m "Update helm tag to ${VERSION}" || echo "No changes to commit"
          git push origin develop || echo "Push failed"
